### ISSUE TITLE
Building on Risc-V fails

### ISSUE THREAD

**Issue by ragnar76** [aranym/aranym#109]
Hi there,

for christmas, i got a StarFive VisionFive 2 which has a Risc-V cpu. When i run configure, i'll get the following error:

- configure: error: Sorry, extended segfault handler not supported on your platform

from config.log the defs for this cpu type is:

hostname = starfive
uname -m = riscv64
uname -r = 5.15.0-starfive
uname -s = Linux
uname -v = #1 SMP Fri Nov 24 07:22:28 UTC 2023
.
.
.
Target: riscv64-linux-gnu

I'm running it with a Debian 12 port

**Comment by th-otto** [comment]
Did you try to configure the normal or the JIT version? Normally, the extended segfault handler should only be required for JIT. And of course, there is no JIT compiler for RISC-V.

**Comment by ragnar76** [comment]
Oh... yes i did.. I've used my configure line i'm using on my x86. will try later again

**Comment by ragnar76** [comment]
yes, jit was the culprit. thanks for the hint
