### ISSUE TITLE
aranym-mmu has disabled pmmu?

### ISSUE THREAD

**Issue by mikrosk** [aranym/aranym#11]
> [mikro@manjaro freemint.git]$ aranym-mmu --version
> ARAnyM 1.0.2
> Using config file: '/home/mikro/.aranym/config'
> Configuration:
> SDL (compiled)   : 1.2.15
> SDL (linked)     : 1.2.15
> CPU JIT compiler : disabled
> FPU JIT compiler : disabled
> Addressing mode  : direct
> Memory check     : page
> Full MMU         : enabled
> FPU              : MPFR
> DSP              : enabled
> DSP disassembler : disabled
> OpenGL support   : enabled
> Native features  : audio bootstrap xhdi ethernet hostfs cdrom(linux,sdl) pci usb scsi osmesa jpeg vdi(opengl,sw) exec clipboard

When downloading latest FreeMiNT snapshot, to my surprise I could see: 'PMMU is requested but not present'. This usually happens when one runs FreeMiNT with aranym-jit.

aranym is fairly recent, built on a linux machine.

**Comment by th-otto** [comment]
> This usually happens when one runs FreeMiNT with aranym-jit.

The JIT version never has MMU, they are incompatible.

**Comment by mikrosk** [comment]
Well, yes, that's the point. The version I'm running (as you can see from the output) is the MMU version, so it definitely should not behave like a JIT version, should it.

**Comment by mikrosk** [comment]
Accidentally, I've bumped into this again. To my surprise, the PMMU is detected & used in the old easymint kernel. So what has changed since then? Well, I added this in 2013:
```
// PMMU detection
//
// A very basic routine. For 000-020 it assumes none,
// for 030 always present and for 040/060 it checks TC's 'E' bit, what is not
// an 100% correct thing to do according to the UM but it seems to work.

_detect_pmmu:
        moveq   #0,d0           // TODO ColdFire PMMU
#ifndef __mcoldfire__
        move.l  d1,-(sp)

        move.l  _mcpu,d1        // check cpu
        cmp.w   #30,d1
        blt.b   pexit           // <030 => no pmmu
        beq.b   pexit1          // 030 => always pmmu for Atari

        dc.w    0x4e7a,0x1003   // movec tc,d1 (040/060)
        and.w   #0x8000,d1      // check 'E' bit
        beq.b   pexit

pexit1: moveq   #1,d0
pexit:  move.l  (sp)+,d1
#endif
        rts
```
It seems that this used to work before (i.e. the E bit was set by `aranym-mmu`) but it isn't since some point?

**Comment by mikrosk** [comment]
Actually, this isn't Aranym's fault. EmuTOS needs to be compiled with `# define CONF_WITH_68040_PMMU 1` or Aranym booted with [setmmu.prg](http://assemsoft.atari.org/#mmu) in AUTO.
