### ISSUE TITLE
Mouse middle button not working anymore

### ISSUE THREAD

**Issue by mikrosk** [aranym/aranym#15]
Unless I have missed something, this nice feature is not longer working. I'm on the latest git source code (compiled against SDL1), when I press the middle button, the cursor stays in aranym and not in the host OS.

Do I have to enable it somehow in the config file? (I have the prehistoric EasyMiNT image + config)

**Comment by mikrosk** [comment]
Interesting, it does seem to work with latest freemint aranym snapshot... so is it really some magic keyword I'm missing in `easymint.conf`?

**Comment by th-otto** [comment]
No, that is purely done by aranym, and there is no setting for this. Unless you have activated WheelEiffel = Yes, then a middle mouse button produces the codes the eiffel interface expects, and does not release the lock anymore.

**Comment by mikrosk** [comment]
Indeed, it has `WheelEiffel = Yes` set. Closing.
