### ISSUE TITLE
Does not compile on MacBook Air. 

### ISSUE THREAD

**Issue by info-lvsys** [aranym/aranym#20]
Hi - was trying to compile on a MacBook Air (MacOS Mojave 10.14.2).

Following the instructions in the INSTALL file:

cd src/Unix/darwin
make
> make: *** No rule to make target `../../../acinclude.m4', needed by `../../../config_i386.h'.  Stop.

Wondering if there are missing instructions :)

Thanks for any help!

**Comment by th-otto** [comment]
Uh, that comments  are outdated and should be removed or changed. The current version of Aranym is only maintained in the XCode project in the src/Unix/MacOSX/MacAranym.xcodeproj folder. Instructions are also there, in README_XCode.rtf (hope they still apply, but at least they are more up-to-date). Automake tools are used from this project too, but they are invoked automatically. Note that aranym by default is build for a *minimum* macos version of 10.5, i'm not sure whether any version of Xcode that works on Mojave still supports that. Also note that aranym has been released only a few days ago where you can pick up binaries in case you can't get it to compile, and that also daily snapshots are available. If you still have problems compiling it yourself, you may also want to look at the automated build script in .travis/build.sh, there you can find at least the needed packages in case the list in the readme isn't enough.

The automated build system uses an image with macos10.12,and Xcode 8.3. 10.13 should also work, but i haven't tried it on mojave yet.

**Comment by info-lvsys** [comment]
OK, sounds good. I'll poke around, thank you!
