### ISSUE TITLE
EmuTOS path (and maybe others) doesn't work with relative path

### ISSUE THREAD

**Issue by mikrosk** [aranym/aranym#21]
Take a working `config` file and place it into a subfolder. Have `emutos` folder on the same level as the subfolder. Regardless of whether `EmuTOS` path is specified as `../emutos/emutos-aranym.img` or `emutos/emutos-aranym.img`, `aranym -c subfolder/config` wont find it.

I think the paths should be always evaluated against the current directory and therefore `emutos/emutos-aranym.img` should work under all circumstances.

**Comment by th-otto** [comment]
Relative paths in the config file should (by design) be evaluated relative to the config file, not the current directory, so ```emutos/emutos-aranym.img``` should theoretically work. Did you try specifiying the name of the config file with an absolute path, eg ```aranym -c $PWD/subfolder/config```?

**Comment by mikrosk** [comment]
You are right, using $PWD fixes it. Not sure if it is still a bug, if not, feel free to close it.

**Comment by th-otto** [comment]
Its a bug somehow, since your original attempt should work, too. I guess some code gets confused when the name of the config file is not absolute. Converting it to an absolute name when specified on the command line should fix it i think.

**Comment by th-otto** [comment]
Should be fixed now.

**Comment by mikrosk** [comment]
Something is not right. When I change emutos, ext2 images and host drives to "../<original path>", first everything looks correct until freemint boot kicks in - it hangs on "installing AKP" table. If I revert my changes, it's fine. I suspect that hostfs.xfs is about to load and hangs somewhere. If I revert my changes (and copy aranym config file to ".."), everything is OK again.

**Comment by th-otto** [comment]
>first everything looks correct until freemint boot kicks in

That's a bit strange. The paths there are only used to locate emutos, mintara.prg, and the disk images. Once those are running (and assuming the disk images are found) they are not used anymore.

Also, the fixed i made just does what you already used with $PWD/<somedir>/config, using the absolute path name of the config file specified on the command line.

**Comment by mikrosk** [comment]
Apologies, it seems that I overlooked something. I re-did the same changes again and it works now. Closing.

**Comment by mikrosk** [comment]
Ha, I knew something is wrong here.

The scenario described in my initial post has indeed been fixed: so I can run aranym-jit -c folder/config and reference ../emutos.img and similar.

However, if I run aranym-jit -c $PWD/folder/config is broken. So the initial workaround doesn't work anymore what is certainly a bug.

**Comment by th-otto** [comment]
Hm, cannot reproduce that here. Both Scenarios work, tested on both linux and cygwin:

```
$ ls -l subfolder/
-rw-r--r-- 1 sebilla users   3351  6. Jun 13:02 config
-rwxr-xr-x 1 sebilla users 367854  6. Jun 13:00 mintara.prg
$ ls -l emutos
-rw-r--r-- 1 sebilla users 524288  6. Jun 12:59 emutos-aranym.img
$ grep -E "EmuTOS|Bootstrap" subfolder/config
EmuTOS = ../emutos/emutos-aranym.img
Bootstrap = mintara.prg
BootstrapArgs = DEBUG_LEVEL=1 BOOT_DELAY=0 MEM_PROT=NO INI_STEP=NO WRITE_BOOT=1
$ ./aranym -c subfolder/config 
ARAnyM 1.1.0
Using config file: '/home/sebilla/atari/aranym/subfolder/config'
...
EmuTOS 2019/06/02 loading from '/home/sebilla/atari/aranym/subfolder/../emutos/emutos-aranym.img'... [OK]

$ ./aranym -c $PWD/subfolder/config 
ARAnyM 1.1.0
Using config file: '/home/sebilla/atari/aranym/subfolder/config'
...
EmuTOS 2019/06/02 loading from '/home/sebilla/atari/aranym/subfolder/../emutos/emutos-aranym.img'... [OK]
```

**Comment by th-otto** [comment]
BTW i just noticed that my previous statement about relative files being looked up relative to the config file is not true in all cases. Files like "nvram" are only loaded from the default config folder (~/.aranym on linux), regardless where the config file is located. I think it has always been like that, but i also think there might be scenarios where it would be better to be able to specify the path, or generally load it from the folder of the config file.

**Comment by mikrosk** [comment]
That's odd. The only difference is that I have mintara.prg also in a separate folder.

Also, aranym starts but the $PWD case just goes into black screen.

I'll try to conduct more tests.

**Comment by th-otto** [comment]
Tested also with
```
$ grep -E "EmuTOS|Bootstrap" subfolder/config
EmuTOS = ../emutos/emutos-aranym.img
Bootstrap = ../emutos/mintara.prg
```
No difference.

**Comment by mikrosk** [comment]
OK, it was my setup's issue after all. I use WSL for everything but the last step (running aranym) so if one specifies $PWD, it translates into /mnt/c/... path which is then handled over to aranym.exe which is a native win32 app, i.e. it doesn't understand non-windows paths.

**Comment by th-otto** [comment]
>which is a native win32 app, i.e. it doesn't understand non-windows paths.

It is a cygwin executable so it would understand cygwin posix paths, but not WSL paths. Is there some tool like cygpath available that translates WSL paths to native windows paths?

**Comment by mikrosk** [comment]
Ah, true. OK, this creates quite a serious mess: WSL paths, cygwin paths, windows paths... 

I'm really not a Windows expert and even less WSL expert, so I don't know. Anyway, this is clearly my fault, WSL is supposed to run WSL executables and command line and not UI Windows (save cygwin) apps.
