### ISSUE TITLE
Feature request: Ubuntu Xenial builds and /usr/local

### ISSUE THREAD

**Issue by mikrosk** [aranym/aranym#23]
As Travis now supports Ubuntu Xenial, would it be possible to built aranym against this environment as well?

My second suggestion would be to package (configure) aranym's snapshots with `/usr/local` prefix, as it is expected that one unpacks its content there as opposed to `/usr` (of course, releases should have `/usr` prefix).

**Comment by mikrosk** [comment]
> why should we suddenly change the prefix for snapshots

For the ability to install both snapshot and release side by side (that would by my use case, anyway)

**Comment by th-otto** [comment]
```
tar -C /usr/local --strip-components=1 -xf <archive>
```
should do that. IIRC there aren't any hardcoded paths in the binary except for the window manager icon.

**Comment by mikrosk** [comment]
> ```
> tar -C /usr/local --strip-components=1 -xf <archive>
> ```
> 
> should do that. IIRC there aren't any hardcoded paths in the binary except for the window manager icon.

actually, it's `tar -C /usr/local --strip-components=2 -xf <archive>` which does the trick here but yes, this is acceptable.

aranym executables work also in Xenial environment but I think it is still worth it to switch over from Trusty.

**Comment by paulwratt** [comment]
re: Xenial, how much has changed from Trusty. ie I have some SDL binaries from early Jessie that still work with Stretch, but maybe that is due to being compiled with GCC 6 in the first place(?).

**Comment by th-otto** [comment]
Changing to xenial was already done by the recent updates form armhf builds. Closing this, unless there are new issues.
