### ISSUE TITLE
wiki manual: linux-m68k links

### ISSUE THREAD

**Issue by paulwratt** [aranym/aranym#30]
The 3 Debian urls in the main documentation (manual.md) section [Linux/m68k on ARAnyM](https://github.com/aranym/aranym/wiki/manual#linuxm68k-on-aranym) need to be updated

In [installation of Debian Woody](https://github.com/aranym/aranym/wiki/manual#installation-of-debian-woody), 1 link needs to be changed from:
`http://ftp.de.debian.org/debian/dists/woody/...`
to:
`http://archive.debian.org/debian/dists/woody/...`

In [installation of Debian Sarge](https://github.com/aranym/aranym/wiki/manual#installation-of-debian-sargel), 2 links need to be changed from:
`http://ftp.debian.org/dists/sarge/...`
to:
`http://archive.debian.org/debian/dists/sarge/...`

Cheers

Paul

**Comment by th-otto** [comment]
Thanks, updated.
