### ISSUE TITLE
EmuTOS Alt key at startup fails due to ARAnyM ROM patch

### ISSUE THREAD

**Issue by vinriviere** [aranym/aranym#36]
I'm using latest ARAnyM snapshot on Windows: aranym-1.1.0-cygwin-i386-503a2549-sdl1.zip

I suspect a regression in the ARAnyM's CPU, specially in the `btst #1,d0` instruction. I found it when examining EmuTOS boot sequence. EmuTOS is a huge testcase, fortunately the problem can be reproduced every time.

Download the testcase archive there:
http://vincent.riviere.free.fr/aranym-testcase.zip
It contains a custom emutos-aranym.img. This is the testcase.

I can observe the correct behaviour with ARAnyM 0.9.16. It displays a single line on the top of the screen at startup:
```
&bootflags=0x00002c70 bootflags=2 &bootdev=0x00000446 bootdev=0
```
But when run with latest ARAnyM snapshot, the displayed line is different:
```
&bootflags=0x00002c70 bootflags=2 &bootdev=0x00000446 bootdev=2
```
Note bootdev=2 at the end: this is wrong, it should be 0.

I also provided a full disassembly in the file dsm.txt (sorry for ugly MIT syntax). See at line 3238, address 00e023b8, label _blkdev_boot. You can see the following sequence:

```
00e023b8:  _blkdev_boot
00e023b8: 4240           	clrw %d0
00e023ba: 1039 0000 2c70 	moveb 0x2c70,%d0
00e023c0: 0800 0001      	btst #1,%d0
00e023c4: 6706           	beqs 0xe023cc
00e023c6: 4279 0000 0446 	clrw 0x446
00e023cc: 0800 0002      	btst #2,%d0
```

Data at address 0x2c70 (bootflags) is put into d0. Then bit 1 is tested. It if is 0, the `beq` instruction is executed. But if it is 1, then `clrw 0x446` (bootdev) should be executed. Thanks to the debug trace, we know that bit 1 was at 1 since bootflags==2. So it seems that `btst #1,d0` didn't properly set the flags.
I have an additional clue. If I patch the binary at address 0x23c4 and replace 6706 with 4e71 to get rid of the beq, then I get the expected result.

Side bug: After displaying the text, I have called EmuTOS `halt()`. It disables the interrupts and calls the stop instruction. In ARAnyM 0.9.16, it worked well, with 0% CPU. In new ARAnyM, I get an ugly text loop in the debug output. This should not happen.

With this testcase, anyone should be able to reproduce the bug very easily. This happens with both non-JIT and JIT versions.

**Comment by vinriviere** [comment]
@czietz has finally discovered the cause of this issue on the EmuTOS Mailing List:
https://sourceforge.net/p/emutos/mailman/message/36706376/

This is related to other problems in issue #10.
ARAnyM patches EmuTOS at runtime. Please don't do that.

**Comment by joysfera** [comment]
Right, I suspected the binary patching because CPU emulation failure would have much worse and broader effects.

We should get rid of that before the next release, it's nasty to binpatch an opensource program.

**Comment by vinriviere** [comment]
This infamous patching has been removed in recent ARAnyM snapshots, when using EmuTOS > 2019-10-30. I consider this issue as fixed, you can close it.

**Comment by th-otto** [comment]
Thanks for reminding. I guess normally the creator of a issue should also be able to close it, but i'm still searching which github setting prevents that .

**Comment by vinriviere** [comment]
Don't look for such option: I actually had a "Comment and close" button. But I simply clicked on "Comment". Regarding to GitHub best practices, it is still unclear who is supposed to close issues (creator or assignee).
