### ISSUE TITLE
warning from configure: unrecognized options: --enable-nfscsi

### ISSUE THREAD

**Issue by ragnar76** [aranym/aranym#39]
Hi there,

today, i got my brand new raspberry pi 4 and i wanted to benchmark it a bit using aranym. i've made a fresh git clone and configure it as follows

```console
pi@raspberrypi:~/src/aranym $ ./configure --prefix=/opt/aranym --enable-hostfs --enable-usbhost --enable-nfjpeg --enable-nfclipbrd --enable-nfvdi --enable-nfscsi --enable-nfexec --enable-nfconfig --enable-ata-cdrom --enable-jit2 --enable-jit-fpu --enable-ethernet 
```

At the very end of configure i've got this warning:

```console
configure: WARNING: unrecognized options: --enable-nfscsi
```

Bernd

**Comment by th-otto** [comment]
There was a typo in the configure script. Try using enable-scsi instead until it  is fixed (but is enabled by default anyway, if it is supported by the os).

**Comment by ragnar76** [comment]
Works like a charm

Thank you :)
