### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [aranym/aranym#4]
Please provide an AppImage for download on https://github.com/aranym/aranym/releases - this would make it much easier for Linux users to try aranym. Thank you!

**Comment by th-otto** [comment]
The AppImages are currently available on https://bintray.com/aranym/aranym-files/snapshots#files/snapshots . Since support for them was added after the 1.0.2 release, there are no AppImages of release versions yet.

**Comment by joysfera** [comment]
Seems like the autobuild didn't quite pick the release properly but I have uploaded the AppImages manually to the releases page so you can go ahead and download them.

**Comment by probonopd** [comment]
Thank you.
