### ISSUE TITLE
Buttons in Setup are to large

### ISSUE THREAD

**Issue by ragnar76** [aranym/aranym#40]
Hi there,
after building aranym (with an error described in #39) i've started aranym to configure it. The buttons in the setup menu are to large (?)  Have a look at the attached screenshot.

I'm using
a Raspberry Pi 4 (2GB)
Raspian Linux 10 (based on Debian Buster)
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
libsdl2 2.0.9 (from debians repository)

It's only cosmetic.The buttons do work.

bye
Bernd

![2019-07-17_22-16](https://user-images.githubusercontent.com/1709576/61409340-52fe8d00-a8e2-11e9-8eab-d856ff8d5c9b.png)

**Comment by th-otto** [comment]
That must be an SDL bug. I've never seen that happen. The whole GUI is drawn using SDL drawing primitives like fill rectangle, draw line etc. Even the font is drawn with raster operations.

**Comment by ragnar76** [comment]
Okay, after compiling the current stable release of SDL from source (version 2.0.9) i have to say, something must be broken with the debian packacke.

![2019-07-18_21-41](https://user-images.githubusercontent.com/1709576/61487108-573fae80-a9a5-11e9-9e8c-0ba5ea05ca22.png)
