### ISSUE TITLE
Issue - JIT and EmuTOS

### ISSUE THREAD

**Issue by Atari260STE** [aranym/aranym#44]
Hello Team,

below on a screenshot you can see strange EmuTOS menu under Aranym JIT (aranym-jit.exe).
It was taken under a new, clean Aranym setup, no hdd, no fdd (config attached)
Used files: emutos-aranym-0.9.12.zip and aranym-1.1.0-cygwin-i386-sdl2-setup.exe. OS: Windows 10.

One remark, aranym-1.1.0-cygwin-i386-sdl2-setup.exe was unpacked manually by me not executed.

Interesting is that there is no that issue under aranym.exe and aranym-mmu.exe.

---EDIT---
one mode issue in that setup, "Aranym setup" dialog box is blinking from time to time, I see EmuTOS desktop icons under it.

![snap000](https://user-images.githubusercontent.com/16839389/67149994-48bda780-f2b2-11e9-8fff-e7cd8f0a2dbd.png)

[config.zip](https://github.com/aranym/aranym/files/3747075/config.zip)

**Comment by czietz** [comment]
It's a duplicate of this bug https://groups.google.com/forum/?hl=en#!topic/aranym/udw7XgJIAPc.

As I had worked out back then, in Aranym 1.1.0 the handling of the 68k CPU flags was "optimized" in a way that is incompatible with 32-bit builds (like the Cygwin one). Since this is a major bug that affects a lot of software (not just EmuTOS), I suggest the Aranym team does a bugfix release.

**Comment by th-otto** [comment]
That should already be fixed. Until a new release is made, i suggest using a snapshot version, available at https://bintray.com/aranym/aranym-files/snapshots/_latestVersion#files

**Comment by Atari260STE** [comment]
I've checked  aranym-1.1.0-cygwin-i386-622b61eb-sdl2.zip.
Menu looks ok, but "Aranym setup" still blinks occasionally.

**Comment by th-otto** [comment]
What do you mean by "blink"? aranym-setup.exe should contain the same files as the zip archive, just turned into a installer executable.

**Comment by vinriviere** [comment]
Second bug (blink) is a duplicate of #26. There is a video in my comment of 25 Jun. It only happens with SDL2.

**Comment by Atari260STE** [comment]
Vincent's #26 covers my blinking issue

**Comment by th-otto** [comment]
Ah ok, almost forgot that. Seems to be an issue with SDL2 and Windows 10 only.

**Comment by Atari260STE** [comment]
I'm closing my ticked due to:

- The first bug is fixed https://github.com/aranym/aranym/commit/18e4f1659e89efee7f3adbde08666aecfe43103d
- The second one is covered by #26
