### ISSUE TITLE
Aranym fails to boot hard disk driver from big drive images

### ISSUE THREAD

**Issue by uweseimet** [aranym/aranym#45]
Aranym fails to boot hard disk drivers (tested with HDDRIVER) from drive images of 500 MB or 50 MB. Images of 5 MB or 512 KB work fine. The same images were tested with Hatari, where all of them were working fine.

**Comment by joysfera** [comment]
can you share a download link to a highly compressed archive of such (empty) hard drive?

**Comment by joysfera** [comment]
Also, Uwe, you as the author of HDDRIVER with the complete source code at hand might have an idea what's going on there, don't you?

**Comment by joysfera** [comment]
Last comment of similar information value as the original bug report: my HDD is 1 GB large and has always booted correctly in ARAnyM.

**Comment by uweseimet** [comment]
Please see the [https://www.hddriver.net/aranym.img.gz](here) for a drive image that exhibits this behavior with TOS 4.04. I already discussed this with Thorsten, but there is no resolution yet. Originally I thought this was a byteswapping issue, but then I noticed that the image size may be relevant, or the number of partitions in the image.
The attached image has ACSI/SCSI byte order, i. e. from an Atari IDE perspective it is byteswapped. Hatari can boot from it, but Aranym cannot, regardless of the byteswapping setting, where the correct one would be "Enabled". The image has 6 equal sized partitions, with the HDDRIVER demo version installed on the first partition.

**Comment by joysfera** [comment]
why have you just closed the issue? Has it resolved automagically?

**Comment by uweseimet** [comment]
Sorry, I pressed the wrong button, just reopened it.

**Comment by paulwratt** [comment]
can the hard drive images be (usefully) mounted from linux?
is it a partition limit issue (4 primary partitions, or a presumption about partition table)?
@joysfera number of partitions? types? size of partition table?
@uweseimet same..

**Comment by joysfera** [comment]
Yes, they can be mounted rather easily nowadays.

**Comment by paulwratt** [comment]
the BeeBoxOS Aranym setup uses 2x partition image files, not a single drive image with 2x partitions, so its not useful for this comparison, but it does show that the C: (BGM) partition was setup using linux (`ByteSwap=Yes`), and the D: (LNX) was setup natively (`ByteSwap=No`).

Q: is it possible the drive image has a boot partition that is not byte swapped, but the others are (or something funny like that, maybe partition table)?

FYI: I read/saw recently (within the last month) that `atari-fdisk` mounts an image byte swapped. Theoretically if there is an issue with the drive image it should also show up on the linux side too

**Comment by DavidGZ** [comment]
By coincidence I hit this issue today. This commit introduced it:
70c9dc44da2b2e2400ea9626937420b1a6f08038

It only affects TOS+HDDRIVER, with EmuTOS system boots fine.

**Comment by joysfera** [comment]
oh really? Did @th-otto make a bug while refactoring the code for patching TOS 4.04?

**Comment by th-otto** [comment]
Unlikely, but not impossible. But that would only have an impact if you are loading TOS 4.04?

**Comment by uweseimet** [comment]
Any chance to get this issue resolved? It appears to be reproducable not just by me.

**Comment by uweseimet** [comment]
Any news on this ticket? I don't have the image file I used for testing anymore, but since the commit that causes this issue has already been identified I would have expected some progress in the meantime. After more than 3 years ;-).

**Comment by uweseimet** [comment]
Just in case somebody wants to get back to this issue: I just re-uploaded an affected image https://www.hddriver.net/aranym.img.gz. Hatari with TOS 4.04 boots from it out of the box, but aranym with TOS 4.04 does not, regardless of the byte order setting.

**Comment by pd95** [comment]
Hi @th-otto

I have encountered the same problem as described in this issue with MacAranym. 
Reverting commit 70c9dc44da2b2e2400ea9626937420b1a6f08038 (which David pointed already out above) fixes the problem.
I think it's a good idea to revert the commit and reintroduce it later on, when the differences are analysed/better understood. Your version of `romdiff.cpp` was much more readable, but it seems that it is not identical to the old patch.

Should I prepare a PR?

Philipp

**Comment by pd95** [comment]
For those interested to test the corrected MacAranym binary, you can find it on my website: https://donzé.ch/atari/software/macaranym/aranym-1.1.0+git-macosx-arm64_x86_64_20230701.dmg

**Comment by joysfera** [comment]
So there's indeed a difference in the content of the ROM after patching:

```
$ cmp -l WORKS DOESNTWORK 
  7973 260 116
  7974 270 161
  7975   4 116
  7976 272 161
  7977 144 116
  7978 362 161
 14744 161 173
 14745 116   0
 14746 161   2
524287 104 111
524288 120 373
```

Wondering why this wasn't checked when the given code was rewritten.

**Comment by joysfera** [comment]
The following code appeared out of nowhere after the https://github.com/aranym/aranym/commit/70c9dc44da2b2e2400ea9626937420b1a6f08038 commit 
(it wasn't part of my original ROMdiff).

```
/* 001F24: ide timeout */
static unsigned char const romdiff_11[6] = {
        0x4e, 0x71, 0x4e, 0x71, 0x4e, 0x71
};
```

It's also basically the only patch code that has an explanation comment (the **ide timeout**). Seems like this was introduced by Thorsten and kinda hidden in the large changeset without proper commit message. Pretty weird.

**Comment by joysfera** [comment]
Fixed by https://github.com/aranym/aranym/commit/989674df504aafd02f28339e7ffe96a26da504a7

**Comment by uweseimet** [comment]
Thank you for fixing this. What I find disappointing, though, is that addressing this problem has taken more than 3 years, even though it was reproducable.

**Comment by joysfera** [comment]
I agree. Especially after Jul 1, 2020 when @DavidGZ identified the exact commit that caused the problem. I'm disappointed.

Anyway, I want to release a new version of ARAnyM ASAP because this bug is part of the last official release.
