### ISSUE TITLE
Close button of Aranym window does not work

### ISSUE THREAD

**Issue by uweseimet** [aranym/aranym#48]
After pressing the Close button (managed by the window manager) Aranym freezes instead of terminating. Operating system is
Linux quattro 4.19.72-gentoo #2 SMP Thu Oct 17 10:00:13 CEST 2019 x86_64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz GenuineIntel GNU/Linux

This happens with the current Aranym sources, but I've been stumbling upon this problem also in the past.

**Comment by th-otto** [comment]
That sounds strange. Could that be something specific to your setup? I've never heard of such problems, and i'm using the close button all the time.

**Comment by uweseimet** [comment]
After some experiments I found a trigger for this issue: When mplayer is running at the same time as aranym and mplayer is actively doing something, e.g. while listening to an internet radio station, aranym hangs when clicking the Close or Shutdown button. As soon as I stop the mplayer audio output (there is no need to stop mplayer itself) aranym terminates.
This is reproducable, so there must be some connection is between (mplayer) audio output and terminating aranym?

**Comment by th-otto** [comment]
Sounds like a problem of pulseaudio. IIRC i had similar problems too, and it happened when SDL shuts down the audio connection. But that bug was fixed long time ago.
I guess this isalso the reason for #47?

**Comment by uweseimet** [comment]
Yes, https://github.com/aranym/aranym/issues/47 is also caused by the sound system being blocked. When playing with the mplayer settings things change, but not in a consistent way.
Anyway, I will close https://github.com/aranym/aranym/issues/48 and https://github.com/aranym/aranym/issues/47, at least from my perspective I'm find with this analysis.
