### ISSUE TITLE
Numpad period key is Delete

### ISSUE THREAD

**Issue by rosenrost** [aranym/aranym#53]
I am running ARAnyM on a Raspberry Pi (BeePi). In this environment the period key (.) on the numeric keypad acts like Delete. Every other key works well. I am using version 1.0.2, but I can confirm this behaviour for the recent master branch, too.

**Comment by th-otto** [comment]
Does that only happen with Aranym?Or with other SDL apps? Or other X11 apps in general?

You can check your X11 keymaps configuration by running xev, then pressing that key.
It should read somthing like
```
KeyRelease event, serial 40, synthetic NO, window 0x7e00001,
    root 0x1d7, subw 0x0, time 433714341, (-631,680), root:(1013,709),
    state 0x10, keycode 91 (keysym 0xffac, KP_Separator), same_screen YES,
    XLookupString gives 1 bytes: (2c) ","
    XFilterEvent returns: False
```

**Comment by rosenrost** [comment]
Unfortunately X11 is not installed on BeePi. Since Hatari uses SDL, too, I compiled H 2.0.0 against SDL 1.2.15 and the key works as expected there.

After that, I tried to compile ARAnyM 1.0.2 (https://github.com/aranym/aranym/archive/ARANYM_1_0_2.tar.gz) against SDL 2.0.10, but make stopped with an error:
```
  CXX    obj_arm/hostscreen.o
./src/./hostscreen.cpp: In member function ‘void HostScreen::reset()’:
./src/./hostscreen.cpp:194:8: error: ‘SDL_VideoInfo’ does not name a type
  const SDL_VideoInfo *videoInfo = SDL_GetVideoInfo();
        ^~~~~~~~~~~~~
./src/./hostscreen.cpp:195:7: error: ‘videoInfo’ was not declared in this scope
  if (!videoInfo->wm_available) {
       ^~~~~~~~~
./src/./hostscreen.cpp: In member function ‘void HostScreen::releaseTheMouse()’:
./src/./hostscreen.cpp:779:8: error: ‘SDL_VideoInfo’ does not name a type
  const SDL_VideoInfo *videoInfo = SDL_GetVideoInfo();
        ^~~~~~~~~~~~~
./src/./hostscreen.cpp:780:7: error: ‘videoInfo’ was not declared in this scope
  if (!videoInfo->wm_available && hiddenMouse) return;
       ^~~~~~~~~
```
Before that, 'make depend' stopped on an error, too:
```
  CC     depend
  CXX    depend
./src/uae_cpu/compiler/compemu_support.cpp:63:21: fatal error: comptbl.h: No such file or directory
 #include "comptbl.h"
                     ^
compilation terminated.
```

**Comment by th-otto** [comment]
SDL_GetVideoInfo is an SDL1 only function. Looks like detection of SDL2 failed for some reason? What was the configure arguments you used?

**Comment by rosenrost** [comment]
> What was the configure arguments you used?

```
# ./configure --prefix=/usr

ARAnyM configuration summary:
SDL version ................... ........ : 2.0.10
```

 
> if X11 is not installed, what driver is used by SDL then?

Oh, I put it wrong: the libraries are present, but the X server is not. These are the libraries from /usr/lib which are loaded (as reported by lsof):
- /usr/lib/arm-linux-gnueabihf/libFLAC.so.8.3.0
- /usr/lib/arm-linux-gnueabihf/libICE.so.6.3.0
- /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0.11.4
- /usr/lib/arm-linux-gnueabihf/libSDL_image-1.2.so.0.8.4
- /usr/lib/arm-linux-gnueabihf/libSM.so.6.0.1
- /usr/lib/arm-linux-gnueabihf/libX11-xcb.so.1.0.0
- /usr/lib/arm-linux-gnueabihf/libX11.so.6.3.0
- /usr/lib/arm-linux-gnueabihf/libXau.so.6.0.0
- /usr/lib/arm-linux-gnueabihf/libXdmcp.so.6.0.0
- /usr/lib/arm-linux-gnueabihf/libXext.so.6.4.0
- /usr/lib/arm-linux-gnueabihf/libXi.so.6.1.0
- /usr/lib/arm-linux-gnueabihf/libXrandr.so.2.2.0
- /usr/lib/arm-linux-gnueabihf/libXrender.so.1.3.0
- /usr/lib/arm-linux-gnueabihf/libXtst.so.6.1.0
- /usr/lib/arm-linux-gnueabihf/libarmmem.so
- /usr/lib/arm-linux-gnueabihf/libasound.so.2.0.0
- /usr/lib/arm-linux-gnueabihf/libasyncns.so.0.3.1
- /usr/lib/arm-linux-gnueabihf/libcaca.so.0.99.19
- /usr/lib/arm-linux-gnueabihf/libjbig.so.0
- /usr/lib/arm-linux-gnueabihf/libjpeg.so.62.2.0
- /usr/lib/arm-linux-gnueabihf/liblz4.so.1.7.1
- /usr/lib/arm-linux-gnueabihf/libogg.so.0.8.2
- /usr/lib/arm-linux-gnueabihf/libpng16.so.16.28.0
- /usr/lib/arm-linux-gnueabihf/libpulse-simple.so.0.1.0
- /usr/lib/arm-linux-gnueabihf/libpulse.so.0.20.1
- /usr/lib/arm-linux-gnueabihf/libsndfile.so.1.0.27
- /usr/lib/arm-linux-gnueabihf/libstdc++.so.6.0.22
- /usr/lib/arm-linux-gnueabihf/libtiff.so.5.2.6
- /usr/lib/arm-linux-gnueabihf/libvorbis.so.0.4.8
- /usr/lib/arm-linux-gnueabihf/libvorbisenc.so.2.0.11
- /usr/lib/arm-linux-gnueabihf/libwebp.so.6.0.2
- /usr/lib/arm-linux-gnueabihf/libxcb.so.1.1.0
- /usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsecommon-10.0.so

**Comment by rosenrost** [comment]
After taking a look at the most recent version of hostscreen.cpp I could fix the lines which led to the compile error.

Unfortunately the programme doesn't recognize any keyboard or mouse input. And the Atari screen uses 1/4 of the host screen being placed in the lower left corner.

**Comment by th-otto** [comment]
>Oh, I put it wrong: the libraries are present, but the X server is not.

Yes, but what driver was then used when you ran Aranym?

> /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0.11.4

There must be something wrong with your installation: why is SDL 2.0.10 reported, but the binary linked against SDL 1.2?

**Comment by rosenrost** [comment]
> Yes, but what driver was then used when you ran Aranym?

How can I check that?

> There must be something wrong with your installation: why is SDL 2.0.10 reported, but the binary linked against SDL 1.2?

Oh, don't mix those two things up: The configure output is my setup to compile Aranym against SDL 2, while the lsof output is based on the pre-installed aranym-jit 1.0.2 which was linked against SDL 1.2.

**Comment by th-otto** [comment]
>How can I check that?

Normally, for SDL2 that could only be the RPI driver. If in doubt, try to apply this patch:
```
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -382,6 +382,7 @@ bool InitAll(void)
                return false;
        }
        atexit(SDL_Quit);
+       infoprint("Using video driver %s", SDL_GetVideoDriverName());
 
        host = new Host();
```

> the lsof output is based on the pre-installed aranym-jit 1.0.2 which was linked against SDL 1.2.

And what has that to do with the problem then?

**Comment by rosenrost** [comment]
With SDL 2.0.10 this returns "Using video driver RPI":
```
infoprint("Using video driver %s", SDL_GetCurrentVideoDriver());
```
With SDL 1.2.5 this returns "Using video driver fbcon":
```
char buf[256];
infoprint("Using video driver %s", SDL_VideoDriverName(buf, 255));
```

**Comment by rosenrost** [comment]
Update:
After installing libudev and recompiling libSDL2 and Aranym, mouse and keyboard input work as expected. The numpad "." key works, too. The issue remains to Aranym and SDL1.

**Comment by th-otto** [comment]
That must be an issue of the console framebuffer device used by SDL1 on rpi. I can't do anything about that. Also you should maybe looking for a newer SDL version, 1.2.15 is the latest official, and the mercurial repo has some more fixes made after the release.
