### ISSUE TITLE
nfosmesa feature fails to build on Linux with SDL + X11

### ISSUE THREAD

**Issue by chewi** [aranym/aranym#54]
A few issues here.

nfosmesa.cpp fails to recognise `X11OpenglContext` when `SDL_VIDEO_DRIVER_X11` is true because osmesa_context.h only defines it when `HAVE_X11_XLIB_H` is also true. The configure check for Xlib.h is only made on Darwin.

It doesn't appear that you've assumed X11 on Linux anywhere but the above `SDL_VIDEO_DRIVER_X11` conditional in nfosmesa.cpp doesn't check whether the X11 driver is actually being used at runtime even though you do this elsewhere. I guess this would fail under Wayland? Does Wayland also need some additional code?

Also if I force `HAVE_X11_XLIB_H` to be true to work around the above then gcc (9.2.0 here) seems to get stuck compiling nfosmesa.cpp. I left it for a few minutes with the CPU hitting 100%. The memory usage was going up but it otherwise didn't appear to be getting anywhere.

**Comment by th-otto** [comment]
>The configure check for Xlib.h is only made on Darwin.

Yes, because on Darwin X11 is not part of macOS, you would have to install an extra package for it, and the x11 driver of SDL is normally not used there.

I just tried on my current system and it compiles without errors. But you are right, the check should always be made.

>I guess this would fail under Wayland? 

Maybe, but the check was made primarly for Darwin.

>seems to get stuck compiling nfosmesa.cpp. I left it for a few minutes with the CPU hitting 100%. >The memory usage was going up but it otherwise didn't appear to be getting anywhere.

That could be. At least one of the generated files is really huge, and mainly contains a big switch statement with ~3000 cases. Takes about 5min on Intel7 @ 3.4GHz to compile just that single file, but eventually will finish. But splitting that would require quite a lot changes to the scripts that generate them.

**Comment by chewi** [comment]
> At least one of the generated files is really huge, and mainly contains a big switch statement with ~3000 cases. Takes about 5min on Intel7 @ 3.4GHz to compile just that single file, but eventually will finish.

Ah, I didn't realise that! And sure enough, I left it longer and it worked.

> I just tried on my current system and it compiles without errors.

I have [proof](https://asciinema.org/a/NNPZTzaVEuXeMSsmwRO01R9mB) that it fails! I've figured it out though. It only fails with SDL2. I'd misread this conditional in SDL_compat.h.

```c
#if !(defined(SDL_VIDEO_DRIVER_QUARTZ) || defined(SDL_VIDEO_DRIVER_COCOA)) || defined(HAVE_X11_XLIB_H)
# define HAVE_X11_XLIB_H 1
#endif
```

I thought that was only evaluating to true on Darwin. I later realised it's the opposite. That explains why it works with SDL1. I then noticed the `#if SDL_VERSION_ATLEAST(2, 0, 0)` and subsequent `#else` further up so SDL2 never sees this code.

I'm not sure why you don't just do `AC_CHECK_HEADERS(X11/Xlib.h)` in all cases but I'll leave you to resolve it one way or another. Even if you do that, the conditional in nfosmesa.cpp should still check `HAVE_X11_XLIB_H`.

**Comment by th-otto** [comment]
Ah, apologies. i only tested with SDL1 but not with SDL2. Should be fixed now.

When you just pull the changes, be sure to rerun autogen.sh to regenerate the configure script, that is not done automatically.
