### ISSUE TITLE
Cant build on raspi 4 using nfosmesa

### ISSUE THREAD

**Issue by ragnar76** [aranym/aranym#58]
Hi there,

i cannot build aranym (429ebdf) with nfosmesa on my raspberry 4. i'm using, beside the raspi, debian 10 and a self build sdl2 (2.0.9). additioninally, all required debian packes (libosmesa6-dev and also a couple of ther lib-gl-*-dev packages) including installed to build aranym from source. 

i was using the following configure options:
 --prefix=/usr
--with-sdl2-prefix=/opt/sdl2
--with-mesa-headers=/usr/include/GL
--enable-nfosmesa
--enable-usbhost
--enable-jit-compiler
--enable-jit2

after a while i get this error:

```
/usr/bin/ld: natfeat/nfosmesa.o: in function `OSMesaDriver::OpenLibrary()':
/home/pi/src/aranym/src/natfeat/nfosmesa.cpp:392: undefined reference to `OSMesaDriver::InitPointersGL(void*)'
/usr/bin/ld: /home/pi/src/aranym/src/natfeat/nfosmesa.cpp:462: undefined reference to `OSMesaDriver::InitPointersGL(void*)'
/usr/bin/ld: natfeat/nfosmesa.o: in function `OSMesaDriver::dispatch(unsigned int)':

```
followed by a couple of errors like this:

```
/usr/bin/ld: /home/pi/src/aranym/src/natfeat/nfosmesa/dispatch-gl.c:6452: undefined reference to `OSMesaDriver::nfglNormal3bv(unsigned int const*)'
/usr/bin/ld: /home/pi/src/aranym/src/natfeat/nfosmesa/dispatch-gl.c:6496: undefined reference to `OSMesaDriver::nfglNormal3s(unsigned int const*)'
/usr/bin/ld: /home/pi/src/aranym/src/natfeat/nfosmesa/dispatch-gl.c:6488: undefined reference to `OSMesaDriver::nfglNormal3i(unsigned int const*)'
/usr/bin/ld: /home/pi/src/aranym/src/natfeat/nfosmesa/dispatch-gl.c:6464: undefined reference to `OSMesaDriver::nfglNormal3f(unsigned int const*)'
/usr/bin/ld: /home/pi/src/aranym/src/natfeat/nfosmesa/dispatch-gl.c:6456: undefined reference to `OSMesaDriver::nfglNormal3d(unsigned int const*)'
/usr/bin/ld: /home/pi/src/aranym/src/natfeat/nfosmesa/dispatch-gl.c:6448: undefined reference to `OSMesaDriver::nfglNormal3b(unsigned int const*)'
```

bye
Bernd

**Comment by th-otto** [comment]
On Samstag, 4. Januar 2020 02:25:59 CET ragnar76 wrote:
> after a while i get this error:

If you have cloned aranym before that commit already, did you regenerate 
Makefile.in etc. by running autogen.sh? Those functions are now in a separate 
file.

**Comment by ragnar76** [comment]
i did yes. but very strangly i can build it with a fresh cloned repo instead of my old one. so i guess, this issue can be closed. :)
