### ISSUE TITLE
aratapif doesn't work with latest kernels?

### ISSUE THREAD

**Issue by mikrosk** [aranym/aranym#62]
To my surprise, I wasn't able to make aranym running in my Arch Linux (after I had reinstalled it a few months ago), using the same set of scripts which used work.

It seems the culprit is either `aratapif` or something related to that `tap0` stuff. This is my config:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 18:31:bf:2c:75:2a brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.13/24 brd 192.168.1.255 scope global dynamic noprefixroute enp3s0
       valid_lft 77265sec preferred_lft 77265sec
    inet6 fe80::5f30:fda2:5a21:1e8/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: tap0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 86:bd:1a:74:79:af brd ff:ff:ff:ff:ff:ff
    inet 192.168.251.1/24 scope global tap0
       valid_lft forever preferred_lft forever
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: aranym@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 192.168.251.1 peer 192.168.251.2
    inet6 fe80::5efe:c0a8:fb01/64 scope link 
       valid_lft forever preferred_lft forever
```

aranym shows:

```
ARAnyM 1.1.0 2019/09/30 (git:622b61eb)
Using config file: '/home/mikro/atari/projects/m68k-atari-mint/bootstrap.git/config/aranym.config'
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Using video driver x11
Using audio driver (null)
Could not open audio: No available audio device
WM Icon not found at /usr/local/share/aranym/wm_icon.bmp
NVRAM not found at '/root/.aranym/nvram'
host_IP: Operation not permitted
TunTap(0): ERROR: aratapif failed (code 2). Ethernet disabled!
```

I'm using this script to enable `tap0`:
```
modprobe tun
chown mikro /dev/net/tun
sleep 1
#tunctl -t tap0 -u mikro
ip tuntap add dev tap0 mode tap user mikro
sleep 1
#ifconfig tap0 192.168.251.1 pointopoint 192.168.251.2 netmask 255.255.255.255 up
ip address add 192.168.251.1/24 dev tap0
ip tunnel add aranym mode ipip local 192.168.251.1 remote 192.168.251.2
ip link set aranym up
iptables -t nat -A POSTROUTING -s 192.168.251.2 -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward
```

and config:
```
[ETH0]
Type = ptp
Tunnel = tap0
HostIP = 192.168.251.1
AtariIP = 192.168.251.2
Netmask = 255.255.255.0
MAC = 00:41:45:54:48:30
```

Standalone `aratapif` shows:
```
[mikro@pc bootstrap.git]$ sudo aratapif tap0 192.168.251.1 192.168.251.2 255.255.255.0 1500
host_IP: Operation not permitted
```

As this used to work and it still works in Ubuntu Xenial (with the same aranym config) I'm wondering what could go wrong here? `Linux pc 5.6.7-1-MANJARO #1 SMP PREEMPT Thu Apr 23 10:50:31 UTC 2020 x86_64 GNU/Linux`

**Comment by paulwratt** [comment]
user `mikro` owns `tap0`, not root - try a group instead and add them both

also if that works and still have problems, in `config` try `type=bridge` (its what BeePi uses - even tho it sets the `ifconfig` with `pointopoint`)

**Comment by mikrosk** [comment]
It doesn't matter - `aratapif` has the setuid bit set, so naturally I tried it first without root. I just wanted to demonstrate it is not a user access issue, root owns everything so there's no way something is not permitted.

**Comment by th-otto** [comment]
On Mittwoch, 29. April 2020 07:55:08 CEST Miro Kropáček wrote:
> root owns everything so there's no way something is not permitted.

Just a guess, but might have something to do with capabilities (see man 
capabilties and man setpriv).

That being said: i currently have similar problems. I have a script that sets 
up a bridge (so it is not using aratapif), which used to work, but now doesn't 
anymore. I don't get any permission errors when i run it, but network does not 
work. Even pinging the router (which is the gateway) does not work.

**Comment by paulwratt** [comment]
what sort of kernels are both of you using (version), and are they 64bit.

I am about to spin up a 64bit Ubuntu on RPi4, theoretically it should have the same problems (due to a later kernel version _or_ need for a 64bit `aratapif` binary).

BTW, does anyone know of any other software that uses a `tune/tap` network interface on linux?

**Comment by th-otto** [comment]
Oh, sorry, missed your question. My current kernel is
```
Linux earendil 5.3.12-1-default #1 SMP Thu Nov 21 07:21:43 UTC 2019 (a6f6081) x86_64 x86_64 x86_64 GNU/Linux
```
from openSUSE.

And no, i'm no aware of any program that uses tun/tap.

**Comment by mikrosk** [comment]
Fixed by changing "Type" to `bridge`. See also https://www.atari-forum.com/viewtopic.php?p=406475&sid=4654e8dc6cc1825d045bc8720331a1a4#p406475.

**Comment by mikrosk** [comment]
> Fixed by changing "Type" to bridge. See also https://www.atari-forum.com/viewtopic.php?p=406475&sid=4654e8dc6cc1825d045bc8720331a1a4#p406475.

OK, I'm an idiot. My memory totally screwed my knowledge of what the setuid bit is and what is it for, i.e. to "allow users to run an executable with the file system permissions **of the executable's owner or group** respectively"

The only reason why it worked in Ubuntu was that I had `aranym` package preinstalled which came with `aratapif` with correct owner (`root`) and took precedence in my `sudo`ed script.

As soon as I changed the owner of `aratapif` also in my build directory, everything started working again. And it took my only 7 months to figure out! Sigh.
