### ISSUE TITLE
Aniplayer video jerky when sound is enabled

### ISSUE THREAD

**Issue by vinriviere** [aranym/aranym#67]
Seen there:
https://www.youtube.com/watch?v=GOkDuLmgWFo&t=2757s

Aniplayer video is jerky when sound is enabled. When I press F3 to disable sound in Aniplayer, the video becomes smooth (can be seen at 46:55).

I didn't make further tests, so I don't currently know if the problem comes from Aniplayer, FreeMiNT, EmuTOS or ARAnyM, of a combination of them. Nevertheless, I open this issue to track investigation progress.

**Comment by mikrosk** [comment]
Definitely a Aniplayer issue. I tested it on my CT60@85 MHz + SuperVidel in CT60 TOS, where the performance is so-so (320x240@25 fps) and I could see it happening, too.

We could ask some FireBee people for a test but I don't think it is necessary.

**Comment by vinriviere** [comment]
Many thanks for your test, @mikrosk. This is the proof that the issue is unrelated to ARAnyM (or even EmuTOS). I suspected this issue to be related to #68, but it is not. So I close the issue.
