### ISSUE TITLE
Haiku OS

### ISSUE THREAD

**Issue by ragnar76** [aranym/aranym#69]
out of curiosity, i've install haiku os on an old laptop. it works like a charm and my first thing to test was: will it run aranym?

Well it does but building with ieee fpu fails (see error message from make) so i had to switch from ieee to uae fpu which works nicely. i dont expect  that will ever be fixed since haiku is a good os to play with but i dont think anyone is using it for daily work.

second thing is, how do i get into the setup without a "pause" key on the keyboard? 
😈
[aranym_build_fail.txt](https://github.com/aranym/aranym/files/4854510/aranym_build_fail.txt)

**Comment by joysfera** [comment]
maybe we could implement something like `aranym --setup` to start and enter the setup immediately (if it isn't there already).

**Comment by th-otto** [comment]
On Dienstag, 30. Juni 2020 23:36:01 CEST ragnar76 wrote:
>  will it run aranym?

Yes, it does. Some time ago i made a few changes to make it compile again. 
There is also a port of it available in https://github.com/haikuports/
haikuports/tree/master/app-emulation/aranym 

At that time however, there was a problem with the JIT version, which made the 
haiku kernel panic. But the normal version should work.

>if it isn't there already

Of course it is ;)
aranym --gui will immediately enter setup.

There you can assign a different key to enter setup. Or you can just edit the 
config file (in newer versions, you can use symbolic names for the keys, so 
you don't have to know the scancode or similar)

**Comment by joysfera** [comment]
@th-otto I read the `aranym --help` twice to ensure it's not there before posting. Apparently my reading abilities after midnight are seriously limited. My fault.

Though the "--gui" sounds like a poor word choice. "--setup" would be better, IMHO. I remember we were fascinated by having an Atari like GUI for the setup but for a newcomer (like me today) it makes little sense to use --gui for entering the setup :-)

**Comment by th-otto** [comment]
It uses getopt() for option parsing, so it should be no problem to support both --setup and --gui

**Comment by th-otto** [comment]
As for the build failure: i can try that at the weekend (i think i still have a haiku environment for virtualbox around somewhere). The missing exp10l()  sounds somewhat familiar to me...

**Comment by paulwratt** [comment]
Haiku has a GCC toolchain, an active developer pool, and a bounty system (outside of haikuports), so if there is anything missing that would enhance ARAnyM, someone just needs to post/ask somewhere

BTW one of the first versions I ever saw of ARAnyM was on Haiku

**Comment by th-otto** [comment]
Should work now. Reason this time was not a bug in mathlib.h regarding usage of that function, but a lack of its declaration in the system's math.h, although the function is there, and seems to work. I've also filed a ticket:
https://dev.haiku-os.org/ticket/16371

BTW, i have configured it on haiku with
```
--prefix=/boot/system --disable-sdl2
```
IIRC, that was taken from the port scripts. At least, the old uae FPU core is really outdated, and i wonder that it actually still compiles ;) But is has the problem that it only uses "double" for math functions, which is not accurate enough to emulate the 68k FPU registers. Another alternative is the MPFR backend, but it is slower.
