### ISSUE TITLE
error: no matching function for call to 'WriteInt32'

### ISSUE THREAD

**Issue by yurivict** [aranym/aranym#77]
clang-10 fails to compile aranym-1.1.0 on FreeBSD 12.2:
```
natfeat/hostfs.cpp:2875:2: error: no matching function for call to 'WriteInt32'
        WriteInt32(filesys + 136, timezone);
        ^~~~~~~~~~
./uae_cpu/cpu_emulation.h:100:20: note: candidate function not viable: no known conversion from 'char *(int, int)' to 'uint32' (aka 'unsigned int') for 2nd argument
static inline void WriteInt32(memptr addr, uint32 l) {put_long(addr, l);}
                   ^
```

**Comment by th-otto** [comment]
Hm, looks a strange compiler behaviour, he is not able to convert an int to an uint32? And what does 'char *(int, int)' mean? I can't see any char * involved there.

**Comment by yurivict** [comment]
```man timezone``` says:
```
SYNOPSIS
     char *
     timezone(int zone, int dst);
```

**Comment by th-otto** [comment]
The code expects a global timezone *variable* there. Looks like that is not available in FreeBSD. I'll try to find a fix. As workaround, you could just use "0" in the meantime.

**Comment by yurivict** [comment]
The patch fixed it.
Thank you!
