### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by sagudev** [aranym/aranym#8]
Can aranym open .st .stx and .msa files

**Comment by th-otto** [comment]
.st files should be just plain images of diskettes, so you should be able to assign them to the floppy path and read them. Others are not directly supported. For .msa files, Hatari has a command line utility to convert them.

**Comment by sagudev** [comment]
What about .stx?

**Comment by th-otto** [comment]
IIRC .stx is mainly used to store raw track data including copy protections. There is no attempt in Aranym to support that. If there was no copy protection on the original disks, you may be able to convert them to .st format and use that.

**Comment by sagudev** [comment]
Steem SSE can use .stx, so I thought aranym could support .stx too. Is possible to open host (linux) terminal in TOS (running in aranym) and HOW

**Comment by joysfera** [comment]
Consider using the mailing list for user questions. https://aranym.github.io/contact.html

**Comment by mikrosk** [comment]
Not a real issue, closing.
