### ISSUE TITLE
Compilation error on Linux x64 with gcc 10.3.0

### ISSUE THREAD

**Issue by uweseimet** [aranym/aranym#82]
With the current sources there is a compillation error:

  CXX      disasm/disasm-x86.o
In file included from ./include/cfgopts.h:16,
                 from cfgopts.cpp:77:
./include/tools.h:100:11: error: ‘uint32_t’ was not declared in this scope; did you mean ‘u_int32_t’?
  100 |  std::map<uint32_t, nativeType> a2n;
      |           ^~~~~~~~
      |           u_int32_t
./include/tools.h:100:31: error: template argument 1 is invalid
  100 |  std::map<uint32_t, nativeType> a2n;
      |                               ^
./include/tools.h:100:31: error: template argument 3 is invalid
./include/tools.h:100:31: error: template argument 4 is invalid
./include/tools.h:101:23: error: ‘uint32_t’ was not declared in this scope; did you mean ‘u_int32_t’?
  101 |  std::map<nativeType, uint32_t> n2a;
      |                       ^~~~~~~~
      |                       u_int32_t
./include/tools.h:101:31: error: template argument 2 is invalid
  101 |  std::map<nativeType, uint32_t> n2a;
      |                               ^

**Comment by th-otto** [comment]
Can you try with current version? Or do you get similar errors also elsewhere? It's a bit confusing since that type is not only used in tools.h

**Comment by uweseimet** [comment]
Maybe other files would also have failed. But now it works until the linking stage:

make[3]: Entering directory '/home/us/aranym/src'
  CXXLD    aranym
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: natfeat/ethernet.o: undefined reference to symbol 'pthread_cancel@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I ran "make distclean ; configure" before compiling, so my setup should be clean.

**Comment by th-otto** [comment]
Please also run autogen.sh, to recreate configure. That should fix the link problem.

**Comment by uweseimet** [comment]
Yes, that fixed it, thank you.
