### ISSUE TITLE
Support for Atari System V (ASV)

### ISSUE THREAD

**Issue by tenox7** [aranym/aranym#84]
Hi

Could you add support for Atari Unix since there already is 040 MMU emulation? Not sure what else is missing? SCSI controller? Thanks!

ASV can be downloaded here: http://atariunix.com/

**Comment by th-otto** [comment]
I'm not sure that will work. ASV was for the TT (030), but the MMU emulation of aranym is for 040. I don't think that ASV will run on 040. Also, i don't know how the kernel has to be loaded.

**Comment by joysfera** [comment]
ARAnyM is not an emulator of existing machines. We're not modifying the HW emulation to support old operating systems but rather encourage authors of modern operating systems to add support for ARAnyM virtual hardware. The few small existing hacks for getting the TOS working were obvious exceptions because TOS wasn't open source and everybody was expecting TOS to work back in last century.

**Comment by tenox7** [comment]
I understand all this, but I saw that it supports Linux m68k which is not TOS/MINT so I thought maybe ASV could work as well.

**Comment by joysfera** [comment]
The Linux is the prime example of what I wrote above - a modern open source operating system that has been modified to run on ARAnyM. If you can modify the ASV to work on M68040 with NatFeats then go ahead with that, otherwise this issue can be closed.

**Comment by th-otto** [comment]
Linux would also work without natfeats (although somewhat slower, especially for IDE access, where the hardware emulation is used). But the culprits are a) the MMU of a 040 is much different from 030, linux supports both, but aranym only emulates 040 and b) the procedure to load a linux kernel is well documented, and aranym uses that to tell the kernel the available hardware, memory etc.

**Comment by tenox7** [comment]
Okay thanks for the detailed explanation! Lets close this :)

**Comment by th-otto** [comment]
Hope that does not disappoint you to much ;) Actually, i think it would be really interesting to get that working. But it won't be an easy task. Maybe, chances with Hatari are better, since Hatari already emulates a 030 CPU&MMU.

**Comment by tenox7** [comment]
Oh not at all. It was a crap shot in the dark just because of that Linux 68k. I didn't think it through. Yeah I saw that Hatari has MMU support for 030 but I don't think they have the right TT NCR SCSI controller. I need to recheck again.
