### ISSUE TITLE
Screenshots (bmp) aren't readable in Mac apps

### ISSUE THREAD

**Issue by chrisridd** [aranym/aranym#85]
The screenshot function writes files using the Microsoft BMP format. Cocoa apps on the Mac cannot read these files as they rely on AppKit which has support for lots of BMP variants but apparently not this one. I couldn't actually find anything on the Mac that worked so I ended up having to find a Windows VM and used Paint to export as PNG. That's a little annoying.

It would be nice if Aranym could write more compatible BMP files. Alternatively, maybe Aranym could use something more clearly cross-platform and portable like (say) PNG.

**Comment by th-otto** [comment]
Aranym currently just uses SDL_SaveBMP() to create those snapshots files. If they cannot be read, then SDL is broken (BTW are you using SDL or SDL2?). I also wonder why Cocoa cannot load them, from what i've seen, SDL uses just the BITMAPCOREHEADER of 40 bytes, which is the simpliest and most compatible version.

Using PNG is not an option, because that would create runtime dependencies we don't want to have (the SDL_LoadBMP function has been replaced for that reason). Also it would not work on windows, because aranym there is build for cygwin, but uses the Win32 version of SDL[2].dll

Might by possible though to replace SDL_SaveBMP as well, but then i need to know what format(s) Cocoa expects.

**Comment by chrisridd** [comment]
I'm using the current "miniPack" non-JIT build, which uses SDL 2.0.14. Indeed, if aranym is just calling SDL_SaveBMP() then it may be an issue in SDL itself. (Unless SDL2 has a way of customising the output, but I can't see anything obvious.)

```
% file snapshots/snap000.bmp 
snapshots/snap000.bmp: PC bitmap, Windows 95/NT4 and newer format, 640 x 480 x 32
```

I suspect it isn't the header itself that's the issue (looks like BITMAPV4HEADER?), but rather the combination of parameters in the header. I can't see any Apple docs describing what Appkit actually supports :-(

**Comment by chrisridd** [comment]
Sure, here's the first bits of an SDL BMP, followed by one written out by Cocoa.

```
cjr@echus snapshots % od -t x1 snap000.bmp | head -20   
0000000    42  4d  7a  c0  12  00  00  00  00  00  7a  00  00  00  6c  00
0000020    00  00  80  02  00  00  e0  01  00  00  01  00  20  00  03  00
0000040    00  00  00  c0  12  00  00  00  00  00  00  00  00  00  00  00
0000060    00  00  00  00  00  00  00  00  ff  00  00  ff  00  00  ff  00
0000100    00  00  00  00  00  ff  20  6e  69  57  00  00  00  00  00  00
0000120    00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
*
0000160    00  00  00  00  00  00  00  00  00  00  ff  ff  ff  ff  ff  ff
0000200    ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
*
2760160    ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  00  00  00  ff  00  00
2760200    00  ff  00  00  00  ff  00  00  00  ff  00  00  00  ff  00  00
*
2761620    00  ff  00  00  00  ff  00  00  00  ff  ff  ff  ff  ff  ff  ff
2761640    ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
*
2765160    ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  00  00  00  ff  00  00
2765200    00  ff  00  00  00  ff  00  00  00  ff  00  00  00  ff  00  00
*
2766620    00  ff  00  00  00  ff  00  00  00  ff  ff  ff  ff  ff  ff  ff
cjr@echus snapshots % od -t x1 /tmp/cocoa.bmp | head -20
0000000    42  4d  c6  da  2b  00  00  00  00  00  36  00  00  00  28  00
0000020    00  00  ee  02  00  00  42  fc  ff  ff  01  00  20  00  00  00
0000040    00  00  90  da  2b  00  23  2e  00  00  23  2e  00  00  00  00
0000060    00  00  00  00  00  00  8f  6a  26  ff  79  49  01  ff  82  4e
0000100    01  ff  7f  50  00  ff  7d  50  00  ff  82  4e  01  ff  82  4e
0000120    01  ff  7f  50  00  ff  80  4f  00  ff  80  4f  00  ff  80  4f
0000140    00  ff  80  4f  00  ff  80  4f  00  ff  80  4f  00  ff  80  4f
0000160    00  ff  80  4f  00  ff  81  50  00  ff  81  50  00  ff  81  50
0000200    00  ff  81  50  00  ff  81  50  00  ff  81  50  00  ff  81  50
*
0000420    00  ff  81  50  00  ff  83  50  00  ff  83  50  00  ff  83  50
0000440    00  ff  83  50  00  ff  83  50  00  ff  83  50  00  ff  83  50
0000460    00  ff  83  50  00  ff  81  50  00  ff  81  50  00  ff  81  50
0000500    00  ff  81  50  00  ff  81  50  00  ff  81  50  00  ff  81  50
0000520    00  ff  81  50  00  ff  83  50  00  ff  83  50  00  ff  83  50
0000540    00  ff  83  50  00  ff  83  50  00  ff  83  50  00  ff  83  50
*
0000760    00  ff  83  50  00  ff  84  51  01  ff  84  51  01  ff  84  51
0001000    01  ff  84  51  01  ff  84  51  01  ff  83  50  00  ff  83  50
0001020    00  ff  83  50  00  ff  84  51  01  ff  84  51  01  ff  84  51
```

So Cocoa writes out BITMAPINFOHEADER (0x28 in the first line) and SDL2 writes out BITMAPV4HEADER instead. I haven't dug any further into the [BMP file format on Wikipedia](https://en.wikipedia.org/wiki/BMP_file_format) or SDL2's code.

**Comment by th-otto** [comment]
IIRC, such hints can also be set by setting a environment variable with the same name.

**Comment by joysfera** [comment]
I'd add the PNG format. Is it really that complicated? Pity I can't look into it right now but the Atari800 (that I consider kind of a sibbling project given the similarity and libSDL usage) has recently been extended not only with better screenshots (in PNG) but also with recording videos.

**Comment by th-otto** [comment]
Using PNG is not really complicated, but will introduce other problems. For example the version on the build system may be different from the version used at runtime (some debian distros still are using PNG 1.4x, while others are using 1.6x). And as noted above, i'm not sure whole well that works on cygwin, where we cannot use a FILE * from SDL to pass to a cygwin DLL or vice versa.
One solution might be to statically link to PNG instead, but then you either have to add the PNG source to the repo, or find some other way to build it.
As for recording videos, i also thought about this once, but then found that it is mostly used for recording games/demos, and that's not a thing that aranym is good at. But maybe its not that complicated, IIRC, Hatari uses a script for most of the work which calls ffmpeg or whatever.

**Comment by chrisridd** [comment]
Excellent, using

```
export SDL_BMP_SAVE_LEGACY_FORMAT=true
```

does change the output format to a usable variant of BMP!

```
cjr@echus Aranym_files % file snapshots/*
snapshots/snap000.bmp: PC bitmap, Windows 95/NT4 and newer format, 640 x 480 x 32
snapshots/snap001.bmp: PC bitmap, Windows 95/NT4 and newer format, 640 x 480 x 32
snapshots/snap002.bmp: PC bitmap, Windows 3.x format, 640 x 480 x 32, image size 1228800, cbSize 1228854, bits offset 54
```

As it is awkward to set environment variables in a Mac GUI app, would it be possible to add a way to set it in the `config` file?

Maybe @joysfera it is possible to write a simple "naive" PNG file without the burden of needing an external library?

**Comment by joysfera** [comment]
So the PNG support is implemented using dynamically linked libpng in Atari800. However, the video recording seems to be implemented "manually", with no external dependency?

FYI @th-otto https://github.com/atari800/atari800/tree/master/src/codecs
