### ISSUE TITLE
Dubious code in nfcdrom_win32.cpp

### ISSUE THREAD

**Issue by czietz** [aranym/aranym#88]
I find this line strange:
https://github.com/aranym/aranym/blob/3bf2875077eb8f7950fd060a0f96802b0b434554/src/natfeat/nfcdrom_win32.cpp#L782
... and assume that it was meant to be...
```cpp
allow.PreventMediaRemoval = (opcode == ATARI_CDROMPREVENTREMOVAL) ? TRUE : FALSE;
```
... or perhaps simply...
```cpp
allow.PreventMediaRemoval = (opcode == ATARI_CDROMPREVENTREMOVAL);
```
... instead.

**Comment by joysfera** [comment]
I'd agree.
