### ISSUE TITLE
Startup issue (black screen, white rectangle)

### ISSUE THREAD

**Issue by uweseimet** [aranym/aranym#99]
After not running it for a long time I re-compiled aranym. After building it with "./autogen.sh && make" and the latest sources, when launching aranym there is a black aranym screen with a white rectangle in the center, that's all.
These are the startup messages:
```
ARAnyM 1.1.0 2021/07/11 (git:69e5e79b)
Using config file: '/home/us/.aranym/config'
Using video driver x11
Using audio driver pulseaudio
WM Icon not found at /usr/local/share/aranym/wm_icon.bmp
ETH0: Error opening /dev/net/tun. Check if module is loaded and privileges are OK
ETH0: NO_NET_DRIVER_WARN 'tap0': No such file or directory
Could not open joystick 0
ARAnyM RTC Timer: /dev/rtc: Permission denied
TOS 4.04 loading... [OK]
Can not load logo from file /usr/local/share/aranym/logo.bmp
WM Icon not found at /usr/local/share/aranym/wm_icon.bmp
```

Platform is gentoo Linux, kernel 5.15.80, gcc 11.3.0, libsdl 1.2.15 and libsdl2 2.24.2.

Attaching my config file failed, neither attaching a .txt nor a .gz file to this ticket worked.

**Comment by uweseimet** [comment]
Just for the record: With the current sources (commit ID f7b168fe) the issue is still there. When launching aranym without a config file after selecting a TOS 4.04 image both Reboot buttons are disabled and I am stuck.

**Comment by joysfera** [comment]
Current git source does not start on my machine either. Not sure if there's a white rectangle or just a completely black screen but it's definitely seriously messed up.

I will have to find time to bisect the several years of commits and find the culprit.

**Comment by th-otto** [comment]
Might also be an SDL issue. I recently realized, that on my distro SDL 1.2 isn't actually SDL 1.2 anymore, but just a wrapper library to SDL 2.x. It therefore also reports a strange version of 1.2.60

**Comment by uweseimet** [comment]
My binary was linked against SDL2. After "make distclean" and configuring with --disable-sdl2 it is linked against SDL 1.2.60, but this does not help. After launching aranym, the aranym window has a completey grey background now, and that's it. Once more. when launching aranym without a config file, after selecting a TOS 4.04 image both Reboot buttons are disabled.
```
>./aranym
ARAnyM 1.1.0 2023/03/19 (git:f7b168fe)
Using config file: '/home/us/.aranym/config'
Using video driver x11
Using audio driver pulseaudio
WM Icon not found at /usr/local/share/aranym/wm_icon.bmp
ETH0: Error opening /dev/net/tun. Check if module is loaded and privileges are OK
ETH0: NO_NET_DRIVER_WARN 'tap0': No such file or directory
Could not open joystick 0
ARAnyM RTC Timer: /dev/rtc: Permission denied
INFO: WARNING: this app used SDL_KillThread(), an unforgivable curse.
This program should be fixed. No thread was actually harmed.
TOS 4.04 loading... [OK]
Can not load logo from file /usr/local/share/aranym/logo.bmp
WM Icon not found at /usr/local/share/aranym/wm_icon.bmp
```

**Comment by joysfera** [comment]
OK, so in my case (I don't claim my issue is the same as @uweseimet reported) the commit causing my startup issue is this one:

commit dc693d130c76cc945269c64c1467f9c6eb45e670
Author: Thorsten Otto <admin@tho-otto.de>
Date:   Mon Jul 25 19:41:43 2022 +0200

    Implement Timer-A emulation (delay-mode only).
    Needed by NetBSD.

 .gitignore                    |   1 +
 ChangeLog                     |   5 +
 src/Unix/host_clock_unix.cpp  |   4 +-
 src/host_clock.cpp            |   8 +-
 src/include/host_clock.h      |   8 +-
 src/include/host_clock_unix.h |   2 +-
 src/include/mfp.h             |  12 +-
 src/main.cpp                  | 111 +++++++++--------
 src/mfp.cpp                   | 277 ++++++++++++++++++++++++++----------------
 9 files changed, 254 insertions(+), 174 deletions(-)

**Comment by th-otto** [comment]
Oops, that's bad. To explain, that emulation was only required to get somewhat further in booting netbsd. However in its current state aranym is still not able to completely boot it. Hatari isn't either, so its quite possible that there is something wrong in the UAE code, especially in the MMU code. That was the main purpose of this patch, to find out what might be going wrong. But i couldn't find it out, and finally gave up.

So there are imho 2 options:
- activate that emulation only when netbsd is running. This would be only for the case someone is going to look into this again
- or simply just revert it

**Comment by joysfera** [comment]
I would vote for quick reverting all NetBSD related changes.

Dne so 25. 3. 2023 8:02 uživatel Thorsten Otto ***@***.***>
napsal:

**Comment by th-otto** [comment]
I wouldn't revert all of them, mainly because new source files were added, and philipp has done changes to the xcode projects to compile them. So that would break xcode builds again.

**Comment by joysfera** [comment]
I would still prefer reverting anything related to NetBSD (xcode related changes could be reverted as well).
The right approach is to modify NetBSD to run on ARAnyM, not the other way round, so ARAnyM should not contain anything NetBSD specific.

**Comment by th-otto** [comment]
I've already reverted the timer-A patch. What remains is mainly the loader (similar to what we do for linux), which is not activated by default.

But i disagree a bit that NetBSD should be modified. If it does not run on aranym, that indicates that something is wrong with the emulation. Linux can be run without any aranym specific changes, too.

**Comment by uweseimet** [comment]
Thank you for addressing this, with the latest changes my problem is gone. I agree with @th-otto, by the way: If NetBSD does not run something is not quite right with aranym.
